version: "3.9"
services:
  backend:
    container_name: node
    image: virajthorat776/node-todo-app
    ports:
      - "8001:8000"
    deploy:
     - mode: replicated
     - replicas: 2

  database:
    container_name: db
    image: mysql
    deploy:
     - mode: replicated
     - replicas: 2
    env_file:
      - .env
