version: "3.3"
services:
  backend:
    container_name: node
    image: virajthorat776/node-todo-app
    ports:
      - "8001:8000"

  database:
    container_name: db
    image: mysql
    env_file:
      - .env
